//! These messages should be autogenerated eventually,
//! but for now we hard-code the ones we need from the
//! FIX 4.4 spec.
//!
use crate::message::common::create_tag;
pub use fefix::fix_values::{Date, Timestamp};
use fefix::tagvalue::{Config, Encoder, EncoderHandle};

#[derive(Debug, Clone)]
pub enum Side {
    Buy,
    Sell,
}

#[derive(Debug, Clone)]
pub struct NewOrderSingle {
    // order details
    pub transact_time: Timestamp,
    pub symbol: String,    // CCY1/CCY2 as string
    pub cl_ord_id: String, // unique order ID assigned by the customer
    pub side: Side,
    pub order_qty: u32,
    pub settlement_date: Date,
    pub currency: String, // the dealt currency

    // allocation
    pub number_of_allocations: u32,
    pub allocation_account: String,
    pub allocation_quantity: u32,
}

#[derive(Debug, Clone)]
pub enum FixMessage {
    NewOrderSingle(NewOrderSingle),
}

pub trait IntoRawMessage {
    fn write(&self, msg: &mut EncoderHandle<Vec<u8>>);

    fn message_type(&self) -> &[u8];
}

impl IntoRawMessage for FixMessage {
    fn write(&self, msg: &mut EncoderHandle<Vec<u8>>) {
        match self {
            FixMessage::NewOrderSingle(order) => {
                // order details
                msg.set_any(create_tag(60), order.transact_time.clone());
                msg.set_any(create_tag(55), order.symbol.as_bytes());
                msg.set_any(create_tag(11), order.cl_ord_id.as_bytes());
                msg.set_any(create_tag(11), order.cl_ord_id.as_bytes());
                let side = match order.side {
                    Side::Buy => "1",
                    Side::Sell => "2",
                };
                msg.set_any(create_tag(54), side);
                msg.set_any(create_tag(38), order.order_qty);
                msg.set_any(create_tag(64), order.settlement_date);
                msg.set_any(create_tag(15), order.currency.as_bytes());

                // allocations
                msg.set_any(create_tag(78), order.number_of_allocations);
                msg.set_any(create_tag(79), order.allocation_account.as_bytes());
                msg.set_any(create_tag(80), order.allocation_quantity);
            }
        }
    }

    fn message_type(&self) -> &[u8] {
        match self {
            FixMessage::NewOrderSingle(_) => b"D",
        }
    }
}

pub(crate) fn generate_message(
    sender_comp_id: &str,
    target_comp_id: &str,
    msg_seq_num: usize,
    message: impl IntoRawMessage,
) -> Vec<u8> {
    let mut buffer = Vec::new();
    let mut encoder: Encoder<Config> = Encoder::default();
    let mut msg = encoder.start_message(b"FIX.4.4", &mut buffer, message.message_type());
    msg.set_any(create_tag(49), sender_comp_id.as_bytes()); // sender comp id
    msg.set_any(create_tag(56), target_comp_id.as_bytes()); // target comp id
    msg.set_any(create_tag(34), msg_seq_num); // msg sequence number
    msg.set_any(create_tag(52), Timestamp::utc_now()); // sending time

    message.write(&mut msg);

    msg.wrap().to_vec()
}
