[workspace]
members = [
    "crates/*",
]
resolver = "2"

[workspace.package]
version = "0.0.10"
authors = ["David Steiner <david_j_steiner@yahoo.co.nz>"]
edition = "2021"
license = "MIT"
readme = "README.md"

[workspace.dependencies]
serde = "^1.0.177"
thiserror = "1.0.50"
tracing = "^0.1.37"
