[package]
name = "hotfix-encoding"
version = "0.0.1"
authors = ["David Steiner <david_j_steiner@yahoo.co.nz>"]
edition = "2021"
license = "MIT"
description = "Message encoding for hotfix, an experimental FIX engine"
keywords = []
readme = "../../README.md"

[dependencies]
serde = { workspace = true, features = ["derive"] }
tracing = { workspace = true }
