name: Test

on:
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: cargo build --verbose
      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -Dclippy::all
      - name: Run tests
        run: cargo test --verbose
